/* empty css                      */import{a as h,S as w,i as n}from"./assets/vendor-DMjJPMAs.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))m(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&m(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function m(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const L="49384745-99fbe35ac45d1d7712b9c9b0c",b="https://pixabay.com/api/",S=15,f=async(e,o=1)=>{try{return(await h.get(b,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:o}})).data}catch(t){throw console.error("Error fetching images:",t),t}};let i;const y=e=>{document.querySelector(".gallery").insertAdjacentHTML("beforeend",e.map(t=>`  
        <li class="gallery-item">  
            <a href="${t.largeImageURL}">  
                <img src="${t.webformatURL}" alt="${t.tags}" />  
            </a>  
            <p>Likes: ${t.likes}</p>  
            <p>Views: ${t.views}</p>  
            <p>Comments: ${t.comments}</p>  
            <p>Downloads: ${t.downloads}</p>  
        </li>  
    `).join("")),i?i.refresh():i=new w(".gallery a",{captionsData:"alt",captionDelay:250})},E=()=>{document.querySelector(".gallery").innerHTML=""},g=()=>{document.querySelector(".loader").style.display="block"},p=()=>{document.querySelector(".loader").style.display="none"},d=e=>{document.querySelector(".load-more").style.display=e?"block":"none"},q=()=>{const e=document.querySelector(".gallery-item");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}},P=document.querySelector(".form"),v=document.querySelector(".load-more");let l="",a=1,u=0;P.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements["search-text"].value.trim(),!l){n.error({title:"Error",message:"Please enter a search term."});return}a=1,E(),d(!1),g();try{const{hits:o,totalHits:t}=await f(l,a);if(u=t,o.length===0){n.warning({title:"No Results",message:"No images found. Try again!"});return}y(o),d(o.length<u)}catch{n.error({title:"Error",message:"An error occurred while fetching images."})}finally{p()}});v.addEventListener("click",async()=>{a+=1,g();try{const{hits:e}=await f(l,a);y(e),q(),a*15>=u&&(d(!1),n.info({title:"End of Results",message:"Sorry, but you have reached the end of search results."}))}catch{n.error({title:"Error",message:"An error occurred while fetching images."})}finally{p()}});
//# sourceMappingURL=index.js.map
