/* empty css                      */import{a as w,S as L,i as a}from"./assets/vendor-DkEYWuMb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const b="49384745-99fbe35ac45d1d7712b9c9b0c",E="https://pixabay.com/api/",y=async(s,t,n)=>{try{return(await w.get(E,{params:{key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}catch(r){throw console.error("Error fetching images:",r),r}};let m;const p=s=>{const t=document.querySelector(".gallery"),n=s.map(r=>`
      <li class="gallery-item">
          <a href="${r.largeImageURL}">
              <img src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
      </li>
  `).join("");t.insertAdjacentHTML("beforeend",n),m?m.refresh():m=new L(".gallery a",{captionsData:"alt",captionDelay:250})},v=()=>{document.querySelector(".gallery").innerHTML=""},h=()=>{document.getElementById("loader").style.display="block"},g=()=>{document.getElementById("loader").style.display="none"},S=document.querySelector(".form"),i=document.querySelector(".load-more");document.getElementById("loader");let d="",l=1;const c=15;let f=0;S.addEventListener("submit",async s=>{if(s.preventDefault(),d=s.target.elements["search-text"].value.trim(),!d){a.error({title:"Error",message:"Please enter a search term."});return}l=1,v(),i.style.display="none",h();try{const{hits:t,totalHits:n}=await y(d,l,c);if(t.length===0){a.warning({title:"No Results",message:"No images found. Try again!"});return}f=n,p(t),t.length<c||l*c>=f?(a.info({title:"End",message:"You have reached the end of the search results."}),i.style.display="none"):i.style.display="block"}catch{a.error({title:"Error",message:"An error occurred while fetching images."})}finally{g()}});i.addEventListener("click",async()=>{l++,h();try{const{hits:s}=await y(d,l,c);p(s);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*c>=f&&(a.info({title:"End",message:"You have reached the end of the search results."}),i.style.display="none")}catch{a.error({title:"Error",message:"An error occurred while fetching images."})}finally{g()}});
//# sourceMappingURL=index.js.map
